FROM node:14-alpine

WORKDIR /app

RUN apk add --no-cache --virtual .build-deps alpine-sdk python

COPY package.json package-lock.json ./

RUN yarn install

COPY . .

RUN yarn run build &&
    apk del .build-deps

CMD yarn start
